import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Quick Start guide sidebar with tutorials
  quickStartSidebar: [
    {
      type: 'category',
      label: 'Quick Start',
      items: [{type: 'autogenerated', dirName: 'quick-start'}],
    },
    // {
    //   type: 'category',
    //   label: 'Tutorials',
    //   items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    // }
  ],
  
  // API Reference sidebar with separate package groups
  apiSidebar: [
    {
      type: 'category',
      label: 'modelence',
      items: [{type: 'autogenerated', dirName: 'api-reference/core'}],
    },
    {
      type: 'category',
      label: '@modelence/react-query',
      items: [{type: 'autogenerated', dirName: 'api-reference/react-query'}],
    },
    {
      type: 'category',
      label: '@modelence/ai',
      items: [{type: 'autogenerated', dirName: 'api-reference/ai'}],
    }
  ],

  // But you can create a sidebar manually
  /*
  quickStartSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
